language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

install:
  - npm install hexo-cli -g
  - npm install

before_script:
  - hexo clean
  - export HEXO_ALGOLIA_INDEXING_KEY=${HEXO_ALGOLIA_INDEXING_KEY}
  - hexo algolia

script:
  - hexo g

after_script:
  - export GH_TOKEN=${GH_TOKEN}
  - export GH_REF=${GH_REF}
  - sed -i "s#https://github.com/yihaoye/yihaoye.github.io.git#https://$GH_TOKEN@$GH_REF#g" _config.yml
  - hexo d

branches:
  only:
    - hexo-version

env:
 global:
   - HEXO_ALGOLIA_INDEXING_KEY: fc8012bde320e7fda40c15290878c9f9
   - GH_REF: github.com/yihaoye/yihaoye.github.io.git
   - secure: "tVye6Gu/s7Mz2AApUGn/9mq6Go1Z/LFZbdQcD/daDR8+c5x70E9M4sDAc23WtBdDCdsEmbFuv9va2NAl0kIh+fhIR02trY2yTCQVhWvuum70yc5D6yNoRzKmm+HOl+aAYUHvXtKqkw4ug3bfOC5Qimj/rQr4HZN3v0tIyDfGCuMw9gezaEMQvuvzUsE1yCchc+yMYh5yF+OfF9bu2Zx4jk8ORx80J7oFbZwU/zRWa6AuMFetzIIYtD/edUbjOayF4BciBbERk5yXUaF6n+1GdC6L75BfphL8hStuaOpC3SMRXStjk6NxNNIySnbKoVTpQ4Qr1yNr+leB/KTYPChJHoT4ZBmDhmPMDxWozXSQW0HsfSKQ2VHDve75f+JzrdGmnEDYNJ9m5BB2XFi6vQ9pfQla7yVQ/Y9vHJ1snj/viMvyXvU14F6OFK3x1JZM2/UG16eLyae9OmqF9aU/xkYG6WkhcrdqQqpxD2TBA+NNRsllPXI1MSOcocfyOdbahUOIbOKSHKbgSq2zB3E47ITr7AU2HtLFDxn7lM7zyN8Jf7ITGK4Hw6rVvvGTu83bkZmSuAEtCeKw34Mf9TGCOzJhmduTEk8uSnzc/tj2oZP3+sotZhFMUky1z40GKR0RdrJB3zfsoMWsmBwMC5bRQxNKSG/HHLgTqg/ojTGKvieP3nk="
