language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

install:
  - npm install hexo-cli -g
  - npm install

# $GH_TOKEN pre seting (https://docs.travis-ci.com/user/environment-variables/)
before_script:
  - sed -i "s#https://github.com/yihaoye/yihaoye.github.io.git#https://$GH_TOKEN@$GH_REF#g" _config.yml
  - cd themes/next
  - git clone https://github.com/theme-next/theme-next-algolia-instant-search source/lib/algolia-instant-search
  - cd ../..
  - hexo clean
  - hexo algolia

script:
  - hexo g

after_script:
  - hexo d

branches:
  only:
    - hexo-version

env:
 global:
   - HEXO_ALGOLIA_INDEXING_KEY: fc8012bde320e7fda40c15290878c9f9
   - GH_REF: github.com/yihaoye/yihaoye.github.io.git
