language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

install:
  - npm install hexo-cli -g
  - npm install

# $GH_TOKEN (i.e. Github Personal API tokens) need pre seting (https://docs.travis-ci.com/user/environment-variables/)
before_script:
  - sed -i "s#https://github.com/yihaoye/yihaoye.github.io.git#https://$GH_TOKEN@$GH_REF#g" _config.yml
  - hexo clean

script:
  - hexo g

after_script:
  - hexo d

branches:
  only:
    - hexo-version

env:
 global:
   - GH_REF: github.com/yihaoye/yihaoye.github.io.git
